routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    return redirect('login');

//    return view('frontend.home');

});

Route::get('newassign', function () {

    $client = \App\Client::orderBy('name')->with('assignment.mkono')->get();

    $guards = \App\Guards::has('client')->get();
    return view('pdf.equipment', compact('client','guards'));

});

Auth::routes();


Route::group(['middleware'=> 'auth'], function () {

    Route::group(['prefix' => 'admin'], function () {

        Route::get('/', function () {

            $whereMonth = \App\Payments::whereMonth('startofmonth', '08')->get();
            return view('welcome',compact('whereMonth'));
        });

        Route::resource('reports','ReportController');

        Route::group(['prefix'=>'print'], function () {

            Route::get('payments', function () {
                $clientE = \App\Client::with('payments.payment')->get();
                return view('pdf.payments', compact('clientE'));

            });
        });

        //Client Routes

        Route::get('client/payments', 'ClientController@payments')->name('payments');

        Route::get('client/active', 'ClientController@activeClient')->name('activeclient');

        Route::get('client/inactive', 'ClientController@inactiveClient')->name('inactiveclient');

        Route::resource('client', 'ClientController');

        Route::resource('payments', 'PaymentsController');

        Route::resource('paids', 'PaidController');

        //Guard Routes

        Route::resource('guard/transfer', 'GuardtransferController');

        Route::get('guard/management/disengange/{guards}', 'GuardsController@disengage')->name('disengageGuard');

        Route::get('guard/management/assign', 'GuardsController@assigns')->name('assignGuard');

        Route::get('guard/management/unassigned', 'GuardsController@unassignedguard')->name('unassignedGuard');

        Route::resource('guard', 'GuardsController');

        Route::resource('attendance', 'AttendanceController');


        //Assignment routes

        Route::resource('assign', 'AssignmentController');

        Route::get('/home', 'HomeController@index')->name('home');
    });
});

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * App\Client
 *
 * @property int $id
 * @property string $name
 * @property int $guards
 * @property string $startDate
 * @property string $endDate
 * @property int $dailyrate
 * @property \Carbon\Carbon|null $created_at
 * @property \Carbon\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Client whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Client whereDailyrate($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Client whereEndDate($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Client whereGuards($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Client whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Client whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Client whereStartDate($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Client whereUpdatedAt($value)
 * @mixin \Eloquent
 * @property string $phonenumber
 * @property string $email
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Client whereEmail($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Client wherePhonenumber($value)
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Guards[] $soldiers
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Payments[] $payments
 */
class Client extends Model
{
    use SoftDeletes;
    protected $fillable = ['*',
    ];

    public function soldiers()
    {
        return $this->hasMany(Assignment::class, 'client_id', 'id');
    }

    public function payments()
    {
        return $this->hasMany(Payments::class, 'client_id', 'id');
    }

    public function assignment()
    {
        return $this->hasMany(Assignment::class, 'client_id', 'id');
    }

    public function clientswithoutguards()
    {
      return  $this::whereDoesntHave('soldiers')->whereNull('endDate')->get();
    }

    public function attendance()
    {
        return $this->hasManyThrough(Attendance::class,Guards::class,'client_id','guard_id');
    }
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Client;
use App\Events\ClientTerminated;
use App\Payments;
use Illuminate\Http\Request;

class ClientController extends Controller
{
    protected $client;
    protected $payments;

    public function __construct(Client $client, Payments $payments)
    {

        $this->client = $client;
        $this->payments = $payments;
    }

    public function payments()
    {
        $all = $this->payments::with(['clients','payment'])->get();
        return view('Client.payments', compact('all'));
    }

    public function activeClient()
    {
        $clients = $this->client::whereHas('soldiers', function ($query) {
            $query->whereNull('endDate');
        })->paginate(100);
        return view('Client.active', compact('clients'));
    }

    public function inactiveClient()
    {
        $clients = $this->client->onlyTrashed()->paginate(10);
        return view('Client.inactive', compact('clients'));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients = $this->client::paginate(100);
        return view('Client.index', compact('clients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Client.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Client $client)
    {
        $patterns = [
            '/^(?:254)(\d{9})/is',
        ];

        $this->validate($request, [
            'name' => ['required', 'unique:clients,name'],
            'start_date' => ['required', 'date'],
            'email' => ['required', 'email'],
            'phone_number' => ['required', function ($attribute, $value, $fail) use ($patterns) {
                foreach ($patterns as $pattern) {
                    if (preg_match($pattern, $value, $matches, PREG_OFFSET_CAPTURE, 0)) {
                        return;
                    }
                    $fail(':attribute must start with 254');
                }
            }, 'unique:clients,phonenumber'],
            'end_date' => ['required', 'date', 'After:start_date', 'nullable'],
            'guards' => ['required', 'numeric'],
            'rate' => ['required'],
        ]);

        $client->name = $request->name;
        $client->startDate = $request->start_date;
        $client->endDate = $request->end_date;
        $client->guards = $request->guards;
        $client->phonenumber = $request->phone_number;
        $client->email = $request->email;
        $client->dailyrate = $request->rate;
        $client->saveOrFail();

        $client->notify();

        return redirect()->route('client.show', $client);

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Client $client
     * @return \Illuminate\Http\Response
     */
    public function show(Client $client)
    {
        $clients = $this->ActiveClients($client);

        $history = $this->ClientHistory($client);

        $payments = $client::with(['payments'])->where('id',$client->id)->get();

        return view('Client.show', compact('clients', 'history','payments'));
    }

    /**
     * @param Client $client
     * @return \Illuminate\Database\Eloquent\Model|null|static
     */
    protected function ActiveClients(Client $client)
    {
        return $client::with(['soldiers' => function ($query) {
            $query->whereNull('endDate');
        }])->where('id', $client->id)->first();
    }

    /**
     * @param Client $client
     * @return \Illuminate\Database\Eloquent\Model|null|static
     */
    protected function ClientHistory(Client $client)
    {
        return $client::with(['soldiers' => function ($query) {
            $query->whereNotNull('endDate');
        }])->where('id', $client->id)->first();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Client $client
     * @return \Illuminate\Http\Response
     */
    public function edit(Client $client)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Client $client
     * @return \Illuminate\Http\Response
     */
    public function destroy(Client $client, Request $request)
    {

        // Send an event that the client has terminated the service.
        // This will in turn disengange all the guards attached to the client.
        ClientTerminated::dispatch($client, $request);
        $client->delete();

        return redirect()->route('client.index');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Client $client
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Client $client)
    {
        $client->name = $request->name;
        $client->startDate = $request->start_date;
        $client->endDate = $request->end_date;
        $client->guards = $request->guards;
        $client->phonenumber = $request->phone_number;
        $client->email = $request->email;
        $client->dailyrate = $request->rate;
        $client->saveOrFail();

        return back();
    }
}

resources/views/Client/active.blade.php
@extends('layouts.bravo')
@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="white-box">
                <h3 class="box-title m-b-0">Clients</h3>
                <p class="text-muted m-b-30">All Active Clients</p>
                <div class="table-responsive">
                    <table class="table table-condensed table-hover">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Phone Number</th>
                            <th>Email</th>
                            <th>Guards</th>
                            <th>Start Date</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php /** @var \App\Client $client */ ?>
                        @foreach ($clients as $client)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td><a href="{{ route('client.show',$client->id) }}">{{ $client->name }}</a></td>
                                <td>{{ $client->phonenumber }}</td>
                                <td>{{ $client->email }}</td>
                                <td>{{ $client->guards }}</td>
                                <td>{{ $client->startDate }}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    <p>Showing {{ $clients->count() }} Clients of {{ $clients->total() }}</p>
                    <div class="pull-right">
                        {{ $clients->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/Client/create.blade.php
@extends('layouts.bravo')
@section('title')
    Add Client
@stop
@section('content')
    <div class="col-md-12">
        <div class="white-box">
            <h3 class="box-title m-b-0">Add Client</h3>
            <p class="text-muted m-b-30 font-13"> Happy we are getting a new client. </p>
            <div class="row">
                <div class="col-sm-12 col-xs-12">
                    <form action="{{ route('client.store') }}" method="post">
                        {{ csrf_field() }}
                        {{-- Label:Name , Attributes:name  --}}
                        <div class="col-md-6 form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="control-label">Name</label>
                            <div class="input-group">
                                <div class="input-group-addon"><i class="ti-user"></i></div>
                                <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}">
                            </div>
                            @if ($errors->has('name'))
                                <span class="help-block">
                                <strong>{{ $errors->first('name') }}</strong>
                            </span>
                            @endif
                        </div>
                        {{-- Label:Email , Attributes:email  --}}
                        <div class="col-md-6 form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="control-label">Email</label>
                            <div class="input-group">
                                <div class="input-group-addon"><i class="ti-email"></i></div>
                                <input id="email" type="text" class="form-control" name="email"
                                       value="{{ old('email') }}">
                            </div>
                            @if ($errors->has('email'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                            @endif
                        </div>
                        {{-- Label:Phone Number , Attributes:phone_number  --}}
                        <div class="col-md-6 form-group{{ $errors->has('phone_number') ? ' has-error' : '' }}">
                            <label for="phone_number" class="control-label">Phone Number</label>
                            <div class="input-group">
                                <div class="input-group-addon"><i class="ti-mobile"></i></div>
                                <input id="phone_number" type="text" class="form-control" name="phone_number"
                                       value="{{ old('phone_number') }}">
                            </div>
                            @if ($errors->has('phone_number'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('phone_number') }}</strong>
                                    </span>
                            @endif
                        </div>
                        {{-- Label:Guards , Attributes:guards  --}}
                        <div class="col-md-6 form-group{{ $errors->has('guards') ? ' has-error' : '' }}">
                            <label for="guards" class="control-label">Guards</label>
                            <div class="input-group">
                                <div class="input-group-addon"><i class="ti-server"></i></div>
                                <input id="guards" type="text" class="form-control" name="guards"
                                       value="{{ old('guards') }}">
                            </div>
                            @if ($errors->has('guards'))
                                <span class="help-block">
                                <strong>{{ $errors->first('guards') }}</strong>
                            </span>
                            @endif
                        </div>
                        {{-- Label:Start Date , Attributes:start_date  --}}
                        <div class="col-md-6 form-group{{ $errors->has('start_date') ? ' has-error' : '' }}">
                            <label for="start_date" class="control-label">Start Date</label>
                            <div class="input-group">
                                <div class="input-group-addon"><i class="ti-alarm-clock"></i></div>
                                <input id="start_date" type="text" class="form-control" name="start_date"
                                       value="{{ old('start_date') }}">
                            </div>
                            @if ($errors->has('start_date'))
                                <span class="help-block">
                                <strong>{{ $errors->first('start_date') }}</strong>
                            </span>
                            @endif
                        </div>

                        {{-- Label:End Date , Attributes:end_date  --}}
                        <div class="col-md-6 form-group{{ $errors->has('end_date') ? ' has-error' : '' }}">
                            <label for="end_date" class="control-label">End Date</label>
                            <div class="input-group">
                                <div class="input-group-addon"><i class="ti-alarm-clock"></i></div>
                                <input id="end_date" type="text" class="form-control" name="end_date"
                                       value="{{ old('end_date') }}">
                            </div>
                            @if ($errors->has('end_date'))
                                <span class="help-block">
                                <strong>{{ $errors->first('end_date') }}</strong>
                            </span>
                            @endif
                        </div>
                        {{-- Label:Rate , Attributes:rate  --}}
                        <div class="col-md-6 form-group{{ $errors->has('rate') ? ' has-error' : '' }}">
                            <label for="rate" class="control-label">Rate</label>
                            <div class="input-group">
                                <div class="input-group-addon"><i class="ti-alarm-clock"></i></div>
                                <input id="rate" type="text" class="form-control" name="rate"
                                       value="{{ old('rate',334) }}">
                            </div>
                            @if ($errors->has('rate'))
                                <span class="help-block">
                                <strong>{{ $errors->first('rate') }}</strong>
                            </span>
                            @endif
                        </div>
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-success waves-effect waves-light m-r-10">Add Client
                            </button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/Client/details.blade.php
<html>
<head>
    <title>Bravo Security</title>
    <script language="JavaScript" type="text/javascript">
        /*setTimeout("window.print();", 10000);*/
    </script>
    <style>
        body {
            padding: 0px;
            margin: 0px;
            font-size: 12px;
        }

        table.data {
            font-family: Verdana;
            font-size: 9px;
            empty-cells: show;
            border: 1px solid #000;
            border-collapse: collapse;
            border-spacing: 0.5rem;
            empty-cells: show;
        }

        table.data td {
            border: 1px solid black;
        }

        table.data td.header {
            background-color: #EDECEB;
            font-size: 13px !important;
            font-weight: bold;
        }

        table.data td.abottom {
            vertical-align: bottom;
            /*font-size: 10px;*/
        }

        span.title {
            font-size: 14px;
            font-weight: bold;
        }

        footer {
            position: fixed;
            bottom: 60px;
            left: 0px;
            right: 0px;
            height: 50px;
        }

        @media all {
            .page-break {
                display: none;
            }
        }

        @media print {
            .page-break {
                display: block;
                page-break-before: always;
                margin: 0px;
                padding: 0px;
            }
        }

        @media screen {
            .page-break {
                display: block;
                page-break-before: always;
                margin: 5px;
                padding: 5px;
            }
        }


    </style>
</head>
<body>
<table cellpadding="2" cellspacing="0" width="100%" class="data">
    <tr>
        <td colspan="9">

            <table width="100%" border=0 cellspacing="0" cellpadding="1" class="data">

                <tr>
                    <td rowspan="6" align="center">
                        <img src="{{ asset('BRAVOLOGO.png') }}" height="100px">
                    </td>
                </tr>
                <?php /** @var \App\Settings $settings */ ?>
                <tr>
                    <td valign="top" colspan="2"><span class="title">Bravo Two Zero Security Service LTD</span></td>
                </tr>

                <tr>
                    <td colspan="2"><b>Address : P.O BOX 132 &mdash; 90138, Makindu</b></td>
                </tr>

                <tr>
                    <td colspan="2"><b>Tel : 0722 393 529 | 0713 642 175</b></td>
                </tr>

                <tr>
                    <td colspan="2"><b>Your security is our commitment! </b></td>
                </tr>

                <tr>
                    <td colspan="4">&nbsp;</td>
                </tr>

                <tr>
                    <td><b>GUARD DETAILS</b></td>
                    <td colspan="4"><b> AUGUST, 2018 BALANCE</b></td>
                </tr>

            </table>

        </td>
    </tr>

</table>
<table cellpadding="2" cellspacing="0" width="100%" class="data">
    <tr>
        <td nowrap class="header"></td>
        <td nowrap class="header">NAME</td>
        <td nowrap class="header">PHONE NUMBER</td>
        <td nowrap class="header">ID NUMBER</td>
        <td nowrap class="header">BALANCE</td>
    </tr>
    <tbody>

    @foreach($client as $clients)

        @foreach($clients->assignment as $cl)
            <tr>
                <td align="right">{{ $cl->mkono->employmentID }}</td>
                <td>{{ $cl->mkono->name }}</td>
                <td>
                    @if( $cl->mkono->phonenumber )
                        {{$cl->mkono->phonenumber}}
                    @endif
                </td>
                <td>
                    @if( $cl->mkono->idnumber )
                        {{$cl->mkono->idnumber}}
                    @endif
                </td>
                <td></td>
            </tr>
        @endforeach
    @endforeach

    <tr>
        <td align="right">BR-1775
            <br>
            <strong>SUPERVISOR</strong>
        </td>
        <td valign="top">DENNIS M. MUTUA</td>
        <td valign="top">0750971652</td>
        <td valign="top">24682478</td>
        <td valign="top"></td>
        <td valign="top"></td>
    </tr>
    <tr>
        <td align="right">
            BR-1867
            <br>
            <strong>STAND-BY GUARD</strong>
        </td>
        <td valign="top">SAMUEL KATUA</td>
        <td valign="top"></td>
        <td valign="top">23375633</td>
        <td valign="top"></td>
        <td valign="top"></td>
    </tr>
    </tbody>
</table>
</body>
</html>

resources/views/Client/inactive.blade.php
@extends('layouts.bravo')
@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="white-box">
                <h3 class="box-title m-b-0">Clients</h3>
                <p class="text-muted m-b-30">All Active Clients</p>
                <div class="table-responsive">
                    <table class="table table-condensed table-hover">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Phone Number</th>
                            <th>Email</th>
                            <th>Guards</th>
                            <th>Start Date</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php /** @var \App\Client $client */ ?>
                        @foreach ($clients as $client)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $client->name }}</td>
                                <td>{{ $client->phonenumber }}</td>
                                <td>{{ $client->email }}</td>
                                <td>{{ $client->guards }}</td>
                                <td>{{ $client->startDate }}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    <p>Showing {{ $clients->count() }} Clients of {{ $clients->total() }}</p>
                    <div class="pull-right">
                        {{ $clients->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/Client/index.blade.php
@extends('layouts.bravo')
@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="white-box">
                <h3 class="box-title m-b-0">Clients</h3>
                <p class="text-muted m-b-30">All Active Clients</p>
                <clients :clients="{{ \App\Client::all() }}"></clients>
            </div>
        </div>
    </div>
@endsection

resources/views/Client/payments.blade.php
@extends('layouts.bravo')
@section('content')
    <div class="col-lg-12 col-sm-12 col-xs-12">
        <div class="white-box">
            <h3 class="box-title">Payments</h3>
            <p class="text-muted m-b-30">Current Payments
                <span class="pull-right">
                <i class="fa fa-file-pdf-o"></i>
                <i class="fa fa-print" onclick="printPayments()"></i>
            </span>
            </p>

            <table class="table table-condensed table-hover">
                <thead>
                <tr>
                    <th>Client Name</th>
                    <th>Invoice No.</th>
                    <th>Current Month</th>
                    <th>Remaining Balance</th>
                    <th>Paid</th>
                </tr>
                </thead>
                <tbody>
                <?php /** @var \App\Payments $value */ ?>
                @foreach ($all as $value)
                    <tr>
                        <td>
                            <a href="{{ route('payments.show',$value->id) }}">{{ $value->clients->name }}</a>
                        </td>
                        <td>{{ $value->invoice }}</td>
                        <td>
                            <span class="label label-success">{{ $value->startofmonth->toFormattedDateString() }}</span>
                            &mdash;
                            <span class="label label-success">{{ $value->endofmonth->toFormattedDateString() }}</span>
                        </td>
                        <td>{{ number_format($value->amountpaid - $value->payment->sum('amount') ,2) }}</td>
                        <td>

                            {{ number_format($value->payment->sum('amount'),2) }}

                        </td>
                    </tr>
                @endforeach

                </tbody>
            </table>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        function printPayments() {
            window.location.assign("/admin/print/payments")
        }
    </script>
@endpush