routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    return redirect('login');

//    return view('frontend.home');

});

Route::get('newassign', function () {

    $client = \App\Client::orderBy('name')->with('assignment.mkono')->get();

    $guards = \App\Guards::has('client')->get();
    return view('pdf.equipment', compact('client','guards'));

});

Auth::routes();


Route::group(['middleware'=> 'auth'], function () {

    Route::group(['prefix' => 'admin'], function () {

        Route::get('/', function () {

            $whereMonth = \App\Payments::whereMonth('startofmonth', '08')->get();
            return view('welcome',compact('whereMonth'));
        });

        Route::resource('reports','ReportController');

        Route::group(['prefix'=>'print'], function () {

            Route::get('payments', function () {
                $clientE = \App\Client::with('payments.payment')->get();
                return view('pdf.payments', compact('clientE'));

            });
        });

        //Client Routes

        Route::get('client/payments', 'ClientController@payments')->name('payments');

        Route::get('client/active', 'ClientController@activeClient')->name('activeclient');

        Route::get('client/inactive', 'ClientController@inactiveClient')->name('inactiveclient');

        Route::resource('client', 'ClientController');

        Route::resource('payments', 'PaymentsController');

        Route::resource('paids', 'PaidController');

        //Guard Routes

        Route::resource('guard/transfer', 'GuardtransferController');

        Route::get('guard/management/disengange/{guards}', 'GuardsController@disengage')->name('disengageGuard');

        Route::get('guard/management/assign', 'GuardsController@assigns')->name('assignGuard');

        Route::get('guard/management/unassigned', 'GuardsController@unassignedguard')->name('unassignedGuard');

        Route::resource('guard', 'GuardsController');

        Route::resource('attendance', 'AttendanceController');


        //Assignment routes

        Route::resource('assign', 'AssignmentController');

        Route::get('/home', 'HomeController@index')->name('home');
    });
});

app/Guards.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * App\Guards
 *
 * @property int $id
 * @property string $name
 * @property string|null $phonenumber
 * @property string|null $idnumber
 * @property string|null $email
 * @property int|null $client_id
 * @property string $employedDate
 * @property string|null $terminationDate
 * @property \Carbon\Carbon|null $created_at
 * @property \Carbon\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Guards whereClientId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Guards whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Guards whereEmail($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Guards whereEmployedDate($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Guards whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Guards whereIdnumber($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Guards whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Guards wherePhonenumber($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Guards whereTerminationDate($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Guards whereUpdatedAt($value)
 * @mixin \Eloquent
 * @property-read \App\Client $client
 * @property string|null $bank_account
 * @property string|null $employmentID
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Guards whereBankAccount($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Guards whereEmploymentID($value)
 */
class Guards extends Model
{
    use SoftDeletes;
    protected $fillable = ['guard_id', 'startDate', 'client_id'];

    public function client()
    {
        return $this->belongsTo(Client::class, 'client_id', 'id')->withDefault(function () {
            return null;
        });
    }

    public function assignments()
    {
        return $this->hasMany(Assignment::class, 'guard_id', 'id');
    }

    public function currentassignments()
    {
        return $this->hasMany(Assignment::class, 'guard_id', 'id')->whereNull('endDate');
    }

    public function standBy()
    {
        return $this->hasOne(Standby::class, 'id', 'guard_id');
    }
}

app/Http/Controllers/GuardsController.php
<?php

namespace App\Http\Controllers;

use App\Assignment;
use App\Client;
use App\Guards;
use Carbon\Carbon;
use Illuminate\Console\Scheduling\Schedule;
use Illuminate\Http\Request;

/**
 * Class GuardsController
 * @package App\Http\Controllers
 */
class GuardsController extends Controller
{
    protected $guards;
    protected $client;

    public function __construct(Guards $guards, Client $client)
    {

        // Terminate a guard
        // Suspend a guard
        // Rehire a guard
        // Guard Attendance
        // Guard Recommendtion letter
        // Guard Termination

        $this->guards = $guards;
        $this->client = $client;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Schedule $schedule)
    {
        $guards = $this->guards::whereHas('assignments', function ($query) {
            $query->whereNull('endDate');

        })->with('client')->get();
        $guards = $this->guards::whereHas('currentassignments', function ($query) {
            $query->whereMonth('startDate','09');

        })->with('client')->get();
        return view('Guard.index', compact('guards'));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function assigns()
    {

        return view('Guard.assign');
    }

    public function unassignedguard()
    {
        // We will get every guard who does not have an assignment and any guard who is not assigned.
        $guards = $this->guards::whereNull('client_id')->paginate();
//        $guards = $this->guards::all();
        return view('Guard.unassigned', compact('guards'));
    }

    /**
     * @param Guards $guards
     * @return \Illuminate\Http\RedirectResponse
     */
    public function disengage(Guards $guards)
    {
        // We will ensure that the guard does not work for the client anymore and is free to be re-assigned or
        // fired by ending their assignment with their current client.

        $employee = $guards::with(['assignments', 'client'])->where('id', $guards->id)->first();
        $employee->assignments()->update([
            'endDate' => Carbon::today()
        ]);
        $employee->client_id = NULL;
        $employee->save();
        return back();


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Guard.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => ['required'],
            'phonenumber' => ['required', 'unique:guards,phonenumber'],
            'idnumber' => ['required', 'unique:guards,idnumber'],
            'employeddate' => ['required', 'date'],
            'employmentID' => ['required', 'unique:guards,employmentID'],
            'email' => ['nullable', 'unique:clients,email'],
        ]);

        $this->guards->name = $request->name;
        $this->guards->phonenumber = $request->phonenumber;
        $this->guards->idnumber = $request->idnumber;
        $this->guards->employedDate = $request->employeddate;
        $this->guards->email = $request->email;
        $this->guards->bank_account = $request->bank_account;
        $this->guards->employmentID = $request->employmentID;
        $this->guards->saveOrFail();
        return redirect()->route('guard.show', [$this->guards->id]);
    }

    /**
     * Display the specified resource.
     *
     */
    public function show($guards)
    {
        // Get the current station of the guard and
        // the history of his whereabouts since he was employed.
        $client = new Client();
        $client->clientswithoutguards();
        
        $guard = $this->CurrentWorkplace($guards);

        $history = $this->GuardHistory($guards);

        $clientswithoutGuards = $this->client->clientswithoutguards();


        return view('Guard.show', compact('guard', 'history', 'clientswithoutGuards'));
    }

    /**
     * @param $guards
     * @return \Illuminate\Database\Eloquent\Model|null|static
     */
    protected function CurrentWorkplace($guards)
    {
        return Guards::with([
            'assignments' => function ($query) {
                $query->whereNull('endDate');
                $query->with('client');
            }
        ])->where('id', $guards)->first();
    }

    /**
     * @param $guards
     * @return \Illuminate\Database\Eloquent\Model|null|static
     */
    protected function GuardHistory($guards)
    {
        return Guards::with([
            'assignments' => function ($query) {
                $query->whereNotNull('endDate');
                $query->with('trashedClient');
            }
        ])->where('id', $guards)->first();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Guards $guards
     * @return \Illuminate\Http\Response
     */
    public function edit(Guards $guards)
    {

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Guards $guards
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Guards $guards)
    {
        $guards = $guards::where('id', $request->id)->first();
        $guards->name = $request->name;
        $guards->phonenumber = $request->phonenumber;
        $guards->idnumber = $request->idnumber;
        $guards->employedDate = $request->employeddate;
        $guards->email = $request->email;
        $guards->bank_account = $request->bank_account;
        $guards->employmentID = $request->employmentID;
        $guards->saveOrFail();

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Guards $guards
     * @return \Illuminate\Http\Response
     */
    public function destroy(Guards $guards){

        $guards->delete();

        return back();
    }
}

resources/views/Guard/attendance.blade.php
@extends('layouts.bravo')
@section('title')
    Attendance
@stop
<?php /** @var \App\Guards $guard */ ?>
@section('content')
    <div class="row">
       <div class="col-md-12">

           <div class="card card-body">
               <h3 class="box-title m-b-0">Attendance</h3>
               <div class="row">
                   <div class="col-sm-12 col-xs-12">
                       <attendance :guards="{{ \App\Guards::whereHas('currentassignments')->with('client')->get() }}"></attendance>
                   </div>
               </div>
           </div>

       </div>
    </div>
@endsection

resources/views/Guard/create.blade.php
@extends('layouts.bravo')
@section('title')
    Add Guard
@stop
@section('content')
    <div class="container">
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form action="{{ route('guard.store') }}" method="post">
                        {{ csrf_field() }}
                        {{-- Label:Name , Attributes:name  --}}
                        <div class="col-md-6 form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="control-label">Name</label>
                            <div>
                                <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}">
                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        {{-- Label:Phone Number , Attributes:phonenumber  --}}
                        <div class="col-md-6 form-group{{ $errors->has('phonenumber') ? ' has-error' : '' }}">
                            <label for="phonenumber" class="control-label">Phone Number</label>
                            <div>
                                <input id="phonenumber" type="text" class="form-control" name="phonenumber"
                                       value="{{ old('phonenumber') }}">
                                @if ($errors->has('phonenumber'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('phonenumber') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        {{-- Label:ID number , Attributes:idnumber  --}}
                        <div class="col-md-6 form-group{{ $errors->has('idnumber') ? ' has-error' : '' }}">
                            <label for="idnumber" class="control-label">ID number</label>
                            <div>
                                <input id="idnumber" type="text" class="form-control" name="idnumber"
                                       value="{{ old('idnumber') }}">
                                @if ($errors->has('idnumber'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('idnumber') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        {{-- Label:Employment ID , Attributes:employmentID  --}}
                        <div class="col-md-6 form-group{{ $errors->has('employmentID') ? ' has-error' : '' }}">
                            <label for="employmentID" class="control-label">Employment ID</label>
                            <div>
                                <input id="employmentID" type="text" class="form-control" name="employmentID"
                                       value="{{ old('employmentID') }}">
                                @if ($errors->has('employmentID'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('employmentID') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        {{-- Label:Bank Account , Attributes:bank_account  --}}
                        <div class="col-md-6 form-group{{ $errors->has('bank_account') ? ' has-error' : '' }}">
                            <label for="bank_account" class="control-label">Bank Account</label>
                            <div>
                                <input id="bank_account" type="text" class="form-control" name="bank_account" value="{{ old('bank_account') }}">
                                @if ($errors->has('bank_account'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('bank_account') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        {{-- Label:Employed Date , Attributes:employeddate  --}}
                        <div class="col-md-6 form-group{{ $errors->has('employeddate') ? ' has-error' : '' }}">
                            <label for="employeddate" class="control-label">Employed Date</label>
                            <div>
                                <input id="employeddate" type="date" class="form-control" name="employeddate"
                                       value="{{ old('employeddate') }}">
                                @if ($errors->has('employeddate'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('employeddate') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        {{-- Label:Email , Attributes:email  --}}
                        <div class="col-md-6 form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="control-label">Email</label>
                            <div>
                                <input id="email" type="text" class="form-control" name="email" value="{{ old('email') }}">
                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="col-md-12">
                            <button class="btn btn-default">Add Guard</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/Guard/show.blade.php
@extends('layouts.bravo')
@section('title')
    Guard: ({{ $guard->name }} | {{ $guard->employmentID }})
@stop
<?php /** @var \App\Guards $guard */ ?>
@section('content')
    <div class="row">
        <div class="col-lg-6 col-sm-6 col-xs-12">
            <div class="white-box">
                <h3 class="box-title">{{ $guard->name }}</h3>
                <p class="text-muted">Phone: <code>{{ $guard->phonenumber }}</code></p>
                <p class="text-muted">Email: <code>{{ $guard->email }}</code></p>
                <p class="text-muted">ID: <code>{{ $guard->idnumber }}</code></p>
                <p class="text-muted">Employment Date: <code>{{ $guard->employedDate }}</code></p>
                <p class="text-muted">Bank Account: <code>{{ $guard->bank_account }}</code></p>

                <div class="table-responsive">
                    <table class="table table-condensed table-hover">
                        <thead>
                        <tr>
                            <th>Client Name</th>
                            <th>Start Date</th>
                            <th>End Date</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($guard->assignments as $value)
                            <tr>
                                <td>{{ $value->client->name}}</td>
                                <td>{{ $value->startDate->toFormattedDateString() }}</td>
                                <td>{{ $value->endDate }}</td>
                                <td>
                                    <form action="" method="post">
                                        <a href="{{ route('disengageGuard',$guard->id) }}"
                                           class="btn btn-danger waves-effect waves-light">
                                            <span>Disengange</span> <i
                                                    class="fa fa-forward m-l-5"></i></a>
                                    </form>

                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
    <div class="row">
        <div class="col-lg-12 col-sm-12 col-xs-12">
            <div class="white-box">
                <h3 class="box-title">Payments</h3>
                <p class="text-muted m-b-30">Assign a client to the guard.</p>


            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-sm-12 col-xs-12">
            <div class="white-box">
                <h3 class="box-title">Guard History</h3>
                <p class="text-muted m-b-30">Assign a client to the guard.</p>
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Start Date</th>
                        <th>End Date</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($history->assignments as $assignment)
                        <tr>
                            <td>{{ $assignment->trashedClient->name }}</td>
                            <td>{{ $assignment->startDate}}</td>
                            <td>{{ $assignment->endDate}}</td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>


            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-sm-12 col-xs-12">
            <div class="white-box">
                <h3 class="box-title">Payroll</h3>
                <p class="text-muted m-b-30">Assign a client to the guard.</p>

                <div class="row">
                    <div class="col-md-12">
                        <form action="{{ route('guard.update',$guard->id) }}" method="post">
                            {{ csrf_field() }}
                            {{ method_field('PATCH') }}
                            <input type="hidden" name="id" value="{{ $guard->id }}">
                            <div class="col-md-6 form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                                <label for="name" class="control-label">Name</label>
                                <div>
                                    <input id="name" type="text" class="form-control" name="name"
                                           value="{{ $guard->name }}">
                                    @if ($errors->has('name'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                            {{-- Label:Phone Number , Attributes:phonenumber  --}}
                            <div class="col-md-6 form-group{{ $errors->has('phonenumber') ? ' has-error' : '' }}">
                                <label for="phonenumber" class="control-label">Phone Number</label>
                                <div>
                                    <input id="phonenumber" type="text" class="form-control" name="phonenumber"
                                           value="{{ $guard->phonenumber }}">
                                    @if ($errors->has('phonenumber'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('phonenumber') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                            {{-- Label:ID number , Attributes:idnumber  --}}
                            <div class="col-md-6 form-group{{ $errors->has('idnumber') ? ' has-error' : '' }}">
                                <label for="idnumber" class="control-label">ID number</label>
                                <div>
                                    <input id="idnumber" type="text" class="form-control" name="idnumber"
                                           value="{{ $guard->idnumber }}">
                                    @if ($errors->has('idnumber'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('idnumber') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                            {{-- Label:Employment ID , Attributes:employmentID  --}}
                            <div class="col-md-6 form-group{{ $errors->has('employmentID') ? ' has-error' : '' }}">
                                <label for="employmentID" class="control-label">Employment ID</label>
                                <div>
                                    <input id="employmentID" type="text" class="form-control" name="employmentID"
                                           value="{{ $guard->employmentID }}">
                                    @if ($errors->has('employmentID'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('employmentID') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                            {{-- Label:Bank Account , Attributes:bank_account  --}}
                            <div class="col-md-6 form-group{{ $errors->has('bank_account') ? ' has-error' : '' }}">
                                <label for="bank_account" class="control-label">Bank Account</label>
                                <div>
                                    <input id="bank_account" type="text" class="form-control" name="bank_account"
                                           value="{{ $guard->bank_account }}">
                                    @if ($errors->has('bank_account'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('bank_account') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                            {{-- Label:Employed Date , Attributes:employeddate  --}}
                            <div class="col-md-6 form-group{{ $errors->has('employeddate') ? ' has-error' : '' }}">
                                <label for="employeddate" class="control-label">Employed Date</label>
                                <div>
                                    <input id="employeddate" type="date" class="form-control" name="employeddate"
                                           value="{{ $guard->employedDate }}">
                                    @if ($errors->has('employeddate'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('employeddate') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                            {{-- Label:Email , Attributes:email  --}}
                            <div class="col-md-6 form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                                <label for="email" class="control-label">Email</label>
                                <div>
                                    <input id="email" type="text" class="form-control" name="email"
                                           value="{{ $guard->email }}">
                                    @if ($errors->has('email'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-12">
                                <button class="btn btn-default">Edit Guard</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12 col-sm-12 col-xs-12">
            <div class="white-box">
                <h3 class="box-title">Clients</h3>
                <p class="text-muted m-b-30">Assign a client to the guard.</p>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Phone Number</th>
                        <th>Email</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($clientswithoutGuards as $client)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $client->name }}</td>
                            <td>{{ $client->phonenumber }}</td>
                            <td>{{ $client->email }}</td>
                            <td>
                                <form action="{{ route('assign.store') }}" method="post">
                                    {{ csrf_field() }}
                                    <input type="hidden" value="{{ $guard->id }}" name="guardid">
                                    <input type="hidden" value="{{ $client->id }}" name="clientid">
                                    <button class="btn btn-info waves-effect waves-light"><span>Assign</span> <i
                                                class="fa fa-forward m-l-5"></i></button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>

            </div>
        </div>
    </div>
@endsection